import { CareConfig } from "./types";

export const mockCareConfigs: Record<string, CareConfig> = {
  "demo-token": {
    patient: {
      id: "demo-token",
      name: "Amira Khan",
    },
   theme: {
      brand: "#f97316",
      brandContrast: "#fff7ed",
      surface: "#fff4e8",
      surfaceMuted: "#ffffff",
      ink: "#2b1c12",
      mutedInk: "#7a5a4d",
      radius: 22,
      displayFont: "Space Grotesk",
      bodyFont: "Plus Jakarta Sans",
      greetingFont: "Sofia",
      headingFont: "Haas Grot Disp Trial",
    },
    layout: [
      {
        id: "welcome",
        type: "welcome",
        props: {
          title: "welcome",
          subtitle:
            "Your case companion for recovery, follow ups & everyday health support!",
          buttonLabel: "Get Started",
          note: "Your info is safe & used for your care purposes only.",
          gradientStart: "#1c1c1c",
          gradientEnd: "rgba(255, 139, 0, 0.8)",
          textMuted: "#919191",
          noteColor: "#ababab",
          buttonColor: "#ff8b00",
          buttonTextColor: "#ffffff",
          blobColor: "#ffe9e1",
        },
      },
      {
        id: "onboarding",
        type: "onboardingSlider",
        props: {
          slides: [
            {
              id: "secure-access",
              title: "Secure Healthcare Access",
              subtitle:
                "Your health data is secure & monitored by certified care teams",
              blobColor: "#ffe9e1",
              illustration: "laptop",
            },
            {
              id: "care-guidance",
              title: "Help is always one tap away",
              subtitle: "Help is available at every step of your recovery",
              blobColor: "#ffe1d6",
              illustration: "chat",
            },
            {
              id: "stay-connected",
              title: "Designed for ease, not\neffort",
              subtitle: "Because managing care should not feel complicated",
              blobColor: "#ffefe8",
              illustration: "highfive",
              ctaLabel: "Next",
            },
          ],
          titleColor: "#444444",
          subtitleColor: "#919191",
          dotActiveColor: "#ff8b00",
          dotInactiveColor: "#ff8b00",
          titleFontSize: "4rem",
          titleFontWeight: 500,
          titleFontFamily: "var(--font-heading)",
          subtitleFontSize: "1.625rem",
          subtitleFontWeight: 400,
          subtitleFontFamily: "var(--font-body)",
          textAlign: "left",
          dotActiveWidth: "1.5rem",
          dotInactiveWidth: "0.55rem",
          dotHeight: "0.4rem",
          dotRadius: "1.25rem",
          dotInactiveOpacity: 0.5,
        },
      },
      {
        id: "connect",
        type: "connectForm",
        props: {
          title: "Use your credential to securely connect with your health records.",
          description: "Use your credential to securely connect with your health records.",
          abhaPlaceholder: "Enter your ABHA Number / Address",
          mobilePlaceholder: "Enter your Mobile Number",
          countryCode: "+91",
          separatorText: "or",
          buttonLabel: "Next",
          buttonDisabledColor: "#fff6ec",
          buttonEnabledColor: "#ff8b00",
          buttonTextColor: "#ffffff",
          borderColor: "#d6c9bb",
          textMuted: "#9b9b9b",
          iconStroke: "#ff8b00",
          blobColor: "#ffe9e1",
        },
      },
      {
        id: "otp",
        type: "otpVerify",
        props: {
          description:
            "We are verifying your number to keep your health data safe.",
          helperText: "Enter the 6 - digit code.",
          resendLabel: "Resend Code",
          buttonLabel: "Next",
          buttonDisabledColor: "#fff6ec",
          buttonEnabledColor: "#ff8b00",
          buttonTextColor: "#ffffff",
          borderColor: "#d6c9bb",
          textMuted: "#9b9b9b",
          iconStroke: "#ff8b00",
          blobColor: "#ffe9e1",
        },
      },
      {
        id: "sosdoes",
        type: "sosDoes",
        props: {
          title: "What SOS does",
          subtitle: "It sends an immediate alert to your care team and ambulatory services for quick response",
          buttonLabel: "Next",
          borderColor: "#d6c9bb",
        },
      },
      {
        id: "sosworks",
        type: "sosWorks",
        props: {
          title: "How SOS Works",
          subtitle: "Tap SOS to let your care team know you need immediate assistance",
          buttonLabel: "Move to dashboard",
          borderColor: "#d6c9bb",
        },
      },
      {
        id: "dashboard",
        type: "dashboard",
        props: {
          welcomeMessage: "Welcome to your dashboard!",
        },
      },
    ],
  },
  "demo-token-2": {
    patient: {
      id: "demo-token-2",
      name: "Rohan Mehta",
    },
    theme: {
      brand: "#a855f7",
      brandContrast: "#faf5ff",
      surface: "#f7f3ff",
      surfaceMuted: "#ffffff",
      ink: "#1f1231",
      mutedInk: "#6b5b7f",
      radius: 14,
      displayFont: "Space Grotesk",
      bodyFont: "Plus Jakarta Sans",
      greetingFont: "Sofia",
      headingFont: "Haas Grot Disp Trial",
    },
    layout: [
      {
        id: "welcome",
        type: "welcome",
        props: {
          title: "welcome",
          subtitle: "Your personal care plan is ready to begin.",
          buttonLabel: "Get Started",
          note: "Your info is safe & used for your care purposes only.",
          gradientStart: "#1c1c1c",
          gradientEnd: "rgba(168, 85, 247, 0.85)",
          textMuted: "#7a6e8b",
          noteColor: "#a69bb8",
          buttonColor: "#a855f7",
          buttonTextColor: "#ffffff",
          blobColor: "#f3e8ff",
        },
      },
      {
        id: "onboarding",
        type: "onboardingSlider",
        props: {
          slides: [
            {
              id: "secure-access",
              title: "Secure Healthcare\nAccess",
              subtitle:
                "Your health data is secure & monitored by certified care teams",
              blobColor: "#f3e8ff",
              illustration: "laptop",
            },
            {
              id: "care-guidance",
              title: "Guided Daily\nRecovery",
              subtitle:
                "Personalized steps, reminders, and follow-ups in one place",
              blobColor: "#ede2ff",
              illustration: "chat",
            },
            {
              id: "stay-connected",
              title: "Stay Connected\nWith Your Team",
              subtitle:
                "Message your care staff anytime and track progress together",
              blobColor: "#f7f0ff",
              illustration: "support",
              ctaLabel: "Next",
            },
          ],
          titleColor: "#444444",
          subtitleColor: "#919191",
          dotActiveColor: "#ff8b00",
          dotInactiveColor: "#ff8b00",
          titleFontSize: "4rem",
          titleFontWeight: 500,
          titleFontFamily: "var(--font-heading)",
          subtitleFontSize: "1.625rem",
          subtitleFontWeight: 400,
          subtitleFontFamily: "var(--font-body)",
          textAlign: "left",
          dotActiveWidth: "1.5rem",
          dotInactiveWidth: "0.55rem",
          dotHeight: "0.4rem",
          dotRadius: "1.25rem",
          dotInactiveOpacity: 0.5,
        },
      },
      {
        id: "connect",
        type: "connectForm",
        props: {
          title: "Use your credential to securely connect with your health records.",
          description: "Use your credential to securely connect with your health records.",
          abhaPlaceholder: "Enter your ABHA Number / Address",
          mobilePlaceholder: "Enter your Mobile Number",
          countryCode: "+91",
          separatorText: "or",
          buttonLabel: "Next",
          buttonDisabledColor: "#fff6ec",
          buttonEnabledColor: "#ff8b00",
          buttonTextColor: "#ffffff",
          borderColor: "#d6c9bb",
          textMuted: "#9b9b9b",
          iconStroke: "#ff8b00",
          blobColor: "#f3e8ff",
        },
      },
      {
        id: "otp",
        type: "otpVerify",
        props: {
          description:
            "We are verifying your number to keep your health data safe.",
          helperText: "Enter the 6 - digit code.",
          resendLabel: "Resend Code",
          buttonLabel: "Next",
          buttonDisabledColor: "#fff6ec",
          buttonEnabledColor: "#ff8b00",
          buttonTextColor: "#ffffff",
          borderColor: "#d6c9bb",
          textMuted: "#9b9b9b",
          iconStroke: "#ff8b00",
          blobColor: "#f3e8ff",
        },
      },
    ],
  },
  "demo-token-3": {
    patient: {
      id: "demo-token-3",
      name: "Lina Torres",
    },
    theme: {
      brand: "#f97316",
      brandContrast: "#fff7ed",
      surface: "#fff4e8",
      surfaceMuted: "#ffffff",
      ink: "#2b1c12",
      mutedInk: "#7a5a4d",
      radius: 22,
      displayFont: "Space Grotesk",
      bodyFont: "Plus Jakarta Sans",
      greetingFont: "Sofia",
      headingFont: "Haas Grot Disp Trial",
    },
    layout: [
      {
        id: "welcome",
        type: "welcome",
        props: {
          title: "welcome",
          subtitle:
            "Your case companion for recovery, follow ups & everyday health support!",
          buttonLabel: "Get Started",
          note: "Your info is safe & used for your care purposes only.",
          gradientStart: "#1c1c1c",
          gradientEnd: "rgba(249, 115, 22, 0.85)",
          textMuted: "#8a6a57",
          noteColor: "#b08a74",
          buttonColor: "#f97316",
          buttonTextColor: "#ffffff",
          blobColor: "#ffead5",
        },
      },
      {
        id: "onboarding",
        type: "onboardingSlider",
        props: {
          slides: [
            {
              id: "secure-access",
              title: "Secure Healthcare\nAccess",
              subtitle:
                "Your health data is secure & monitored by certified care teams",
              blobColor: "#ffead5",
              illustration: "laptop",
            },
            {
              id: "care-guidance",
              title: "Guided Daily\nRecovery",
              subtitle:
                "Personalized steps, reminders, and follow-ups in one place",
              blobColor: "#ffe2c9",
              illustration: "chat",
            },
            {
              id: "stay-connected",
              title: "Stay Connected\nWith Your Team",
              subtitle:
                "Message your care staff anytime and track progress together",
              blobColor: "#fff1e6",
              illustration: "support",
              ctaLabel: "Next",
            },
          ],
          titleColor: "#444444",
          subtitleColor: "#919191",
          dotActiveColor: "#ff8b00",
          dotInactiveColor: "#ff8b00",
          titleFontSize: "4rem",
          titleFontWeight: 500,
          titleFontFamily: "var(--font-heading)",
          subtitleFontSize: "1.625rem",
          subtitleFontWeight: 400,
          subtitleFontFamily: "var(--font-body)",
          textAlign: "left",
          dotActiveWidth: "1.5rem",
          dotInactiveWidth: "0.55rem",
          dotHeight: "0.4rem",
          dotRadius: "1.25rem",
          dotInactiveOpacity: 0.5,
        },
      },
      {
        id: "connect",
        type: "connectForm",
        props: {
          title: "Use your credential to securely connect with your health records.",
          description: "Use your credential to securely connect with your health records.",
          abhaPlaceholder: "Enter your ABHA Number / Address",
          mobilePlaceholder: "Enter your Mobile Number",
          countryCode: "+91",
          separatorText: "or",
          buttonLabel: "Next",
          buttonDisabledColor: "#fff6ec",
          buttonEnabledColor: "#ff8b00",
          buttonTextColor: "#ffffff",
          borderColor: "#d6c9bb",
          textMuted: "#9b9b9b",
          iconStroke: "#ff8b00",
          blobColor: "#ffead5",
        },
      },
      {
        id: "otp",
        type: "otpVerify",
        props: {
          description:
            "We are verifying your number to keep your health data safe.",
          helperText: "Enter the 6 - digit code.",
          resendLabel: "Resend Code",
          buttonLabel: "Next",
          buttonDisabledColor: "#fff6ec",
          buttonEnabledColor: "#ff8b00",
          buttonTextColor: "#ffffff",
          borderColor: "#d6c9bb",
          textMuted: "#9b9b9b",
          iconStroke: "#ff8b00",
          blobColor: "#ffead5",
        },
      },
    ],
  },
};
